spring:
  application:
    name: sociojustice-lite-api
  datasource:
    url: jdbc:postgresql://localhost:5432/sociojustice_lite
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 3000
