spring:
  application:
    name: sociojustice-lite-api
  datasource:
    url: jdbc:postgresql://localhost:5432/sociojustice
    username: sj
    password: sj
  flyway:
    enabled: false
    locations: classpath:db/migration
    schemas: public
    clean-disabled: false
    clean-on-validation-error: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.flywaydb.core.internal: debug

server:
  port: 3000

jwt:
  secret: "dev-only-change-this-please-32b-min"
  expires-in-seconds: 86400
