# --- Datasource Postgres (adapte les valeurs) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/sociojustice
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.maximum-pool-size=5

# --- JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# --- Flyway ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
